# Generated by Django 5.0.1 on 2024-02-13 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0003_alter_comment_options_comment_date_comment_paste_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastes',
            name='views',
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pastes.comment'),
        ),
        migrations.AlterField(
            model_name='pastes',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='PasteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('pastes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastes.pastes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pastes')},
            },
        ),
    ]
